### ISSUE TITLE
Search Firestore with Typesense extension is not syncing data between firestore db and typesense cloud

### ISSUE THREAD

**Issue by nitingn** [typesense/typesense#1075]
## Steps to reproduce
I have tried backfilldata approach as well updating the records in firestore manually to trigger sync. I keep getting ;

ERROR 2023-06-29T08:10:40.730161Z [resource.labels.functionName: ext-firestore-typesense-search-indexToTypesenseOnFirestoreWrite] [labels.executionId: ks21gjza3nto] Error: Request failed with HTTP code 400 | Server said: Field **`detailedMeaningDescription` has been declared in the schema, but is not found in the document. at ApiCall.customErrorForRe**sponse (/workspace/node_modules/typesense/lib/Typesense/ApiCall.js:220:21) at ApiCall.performRequest (/workspace/node_modules/typesense/lib/Typesense/ApiCall.js:118:48) at processTicksAndRejections (internal/process/task_queues.js:95:5) at async /workspace/src/indexToTypesenseOnFirestoreWrite.js:24:16

I have dropped all colletion data and recreated .still getting same error
  

A collection in Firestore:
![image](https://github.com/typesense/typesense/assets/67514561/d42f1f94-335c-4e1b-92b2-cb63b93695be)

Schema in Typesense:

{
    "created_at": 1687929043,
    "default_sorting_field": "",
    "enable_nested_fields": true,
    "fields": [
        {
            "facet": false,
            "index": true,
            "infix": false,
            "locale": "",
            "name": "searchWord",
            "optional": false,
            "sort": false,
            "type": "string[]"
        },
        {
            "facet": false,
            "index": true,
            "infix": false,
            "locale": "",
            "name": "searchSourceLangSynonym",
            "optional": false,
            "sort": false,
            "type": "string"
        },
        {
            "facet": false,
            "index": true,
            "infix": false,
            "locale": "",
            "name": "examples",
            "optional": false,
            "sort": false,
            "type": "string[]"
        },
        {
            "facet": false,
            "index": false,
            "infix": false,
            "locale": "",
            "name": "imageUrls",
            "optional": true,
            "sort": false,
            "type": "string[]"
        },
        {
            "facet": true,
            "index": true,
            "infix": false,
            "locale": "",
            "name": "detailedMeaningDescription",
            "optional": false,
            "sort": false,
            "type": "string[]"
        }
    ],
    "name": "tilipadaDictionary",
    "num_documents": 0,
    "symbols_to_index": [],
    "token_separators": []
}

## Expected Behavior

The fields in firestore such as searchWord,detailedMeaningDescription,imageUrls,searchSourceLangSynonym,examples should be synced to type sense seemsesly.
And later if i additional fields of firestore collection to typesense schema , it should sync seamlessly.

## Metadata

**Typesense Version**: 0.24.1 cloud

**OS**:

**Comment by jasonbosco** [comment]
Could you share a screenshot of your Firestore extension configuration?

**Comment by nitingn** [comment]
> Could you share a screenshot of your Firestore extension configuration?

![image](https://github.com/typesense/typesense/assets/67514561/542b5221-41c9-483b-a5a8-5543ff3462f7)


Is it necessary to give all the fields  which were declared in typesense schema in Firestroe colletion fields value ?

**Comment by jasonbosco** [comment]
> Is it necessary to give all the fields which were declared in typesense schema in Firestroe colletion fields value ?

That's correct. Or you can leave it blank to sync all fields. 

The current configuration in your screenshot will only sync the `searchWord` field from Firestore into Typesense. That's why the error you saw said `Field detailedMeaningDescription has been declared in the schema, but is not found in the document`.
