### ISSUE TITLE
Self-Hosted Write Limits

### ISSUE THREAD

**Issue by samo012** [typesense/typesense#1256]
## Description
Hello,

I have a few questions. I've deployed Typesense to 3 Google Compute instances (2vCPUs & 8GB RAM) with a load balancer. My current setup works great for serving quick search results but fails when upserting 100k records in a queue with `HTTP 503 Lagging or Not Ready`.  I was wondering if there are any write limits to the self-hosted version or if it is just based on CPU limitations. If it’s based on CPU, what do you suggest setting the `--healthy-write-lag` flag in the server config to? Is this value equal to writes per second or is it queue-based? My system triggers an update per record individually so I'm using upsert over import. Importing in batches is probably the better solution, is this also affected by `--healthy-write-lag` or would I run into the same issue? Another solution is increasing the number of cores but more costly. I'm also going to try and reduce my indexed fields.

Each instance has 20GB SSDs which are almost at capacity with only 4 collections with 20k documents each. My next question is where is all this storage being depleted from? Should I run a scheduled cleanup of logs, state, or some other directory? 

Any help is appreciated.
Thanks

**Comment by jasonbosco** [comment]
> I was wondering if there are any write limits to the self-hosted version or if it is just based on CPU limitations.

No, there are no limits in the self-hosted version. Typesense will use all available CPU cores. 

>  If it’s based on CPU, what do you suggest setting the --healthy-write-lag flag in the server config to

It's dependent on what your write pattern looks like, so it's best to experiment with values in the 10000s of then tweak from there. 

>  Is this value equal to writes per second or is it queue-based?

This is the number of write API calls that will be accepted into the write queue, before Typesense will reject additional writes with a `HTTP 503 Lagging or Not Ready`.

Here's a more detailed guide on how to handle this back-pressure mechanism: https://typesense.org/docs/guide/syncing-data-into-typesense.html#handling-http-503s

> My system triggers an update per record individually so I'm using upsert over import.

This is probably the core of the issue if you're sending a large number of individual writes. Processing 100K individual API calls is going to be at least an order of magnitude slower than processing 100K writes in a single batch import API call. 

For eg, I've been able to upsert 2.2M docs, in a single batch import API call in about 3.3 minutes. 

> Each instance has 20GB SSDs which are almost at capacity with only 4 collections with 20k documents each. My next question is where is all this storage being depleted from?

The client library has automatic retries configured on failure. So it's likely that all these retries are sending duplicate data to Typesense when they see a 503, and that's filling up disk space. You want to increase the timeout interval and the retry interval in the client library. 

> Should I run a scheduled cleanup of logs, state, or some other directory?

This is normally not needed, but you could try running a [compaction](https://typesense.org/docs/0.25.1/api/cluster-operations.html#compacting-the-on-disk-database) for the on-disk DB.

**Comment by jdriscoll98** [comment]
@jasonbosco Have you run into issues importing 10k+ documents with auto embedding fields using openAI as the remote embedding model? I'm curious how typesense handles the rate limits from openai.

**Comment by jdriscoll98** [comment]
For reference I'm creating a new collection with auto embedded fields and importing my previous documents. I'm not getting any import errors in the response from .import() but I see this in the logs a lot

```
E20230927 21:59:06.460528    29 http_proxy.cpp:75] Proxy call failed, status_code: 408, timeout_ms:  60000, try: 2, num_try: 2
E20230927 21:59:06.465754    36 http_client.cpp:162] CURL timeout. Time taken: 3.00148, URL: https://api.openai.com/v1/embeddings
E20230927 21:59:06.465849    36 http_proxy.cpp:75] Proxy call failed, status_code: 408, timeout_ms:  60000, try: 2, num_try: 2
E20230927 21:59:06.488551    28 http_client.cpp:162] CURL timeout. Time taken: 3.00162, URL: https://api.openai.com/v1/embeddings
E20230927 21:59:06.488662    28 http_proxy.cpp:75] Proxy call failed, status_code: 408, timeout_ms:  60000, try: 2, num_try: 2
E20230927 21:59:09.388108    26 http_client.cpp:162] CURL timeout. Time taken: 3.00354, URL: https://api.openai.com/v1/embeddings
E20230927 21:59:09.388371    26 http_proxy.cpp:75] Proxy call failed, status_code: 408, timeout_ms:  60000, try: 1, num_try: 2
E20230927 21:59:09.394610    31 http_client.cpp:162] CURL timeout. Time taken: 3.00393, URL: https://api.openai.com/v1/embeddings
E20230927 21:59:09.394610    39 http_client.cpp:162] CURL timeout. Time taken: 3.00299, URL: https://api.openai.com/v1/embeddings
E20230927 21:59:09.394920    31 http_proxy.cpp:75] Proxy call failed, status_code: 408, timeout_ms:  60000, try: 1, num_try: 2
E20230927 21:59:09.395124    39 http_proxy.cpp:75] Proxy call failed, status_code: 408, timeout_ms:  60000, try: 1, num_try: 2
E20230927 21:59:09.442670    35 http_client.cpp:162] CURL timeout. Time taken: 3.00155, URL: https://api.openai.com/v1/embeddings
E20230927 21:59:09.442793    35 http_proxy.cpp:75] Proxy call failed, status_code: 408, timeout_ms:  60000, try: 1, num_try: 2
E20230927 21:59:09.760905    33 http_client.cpp:162] CURL timeout. Time taken: 3.00413, URL: https://api.openai.com/v1/embeddings
E20230927 21:59:09.761054    33 http_proxy.cpp:75] Proxy call failed, status_code: 408, timeout_ms:  60000, try: 1, num_try: 2
E20230927 21:59:09.762821    32 http_client.cpp:162] CURL timeout. Time taken: 3.00321, URL: https://api.openai.com/v1/embeddings
E20230927 21:59:09.763092    32 http_proxy.cpp:75] Proxy call failed, status_code: 408, timeout_ms:  60000, try: 1, num_try: 2
```

**Comment by jasonbosco** [comment]
I have indeed seen timeouts with OpenAI APIs, depending on time of day (may be due to traffic patterns on the OpenAI side). 

You can control remote embedding timeouts are retries using `remote_embedding_timeout_ms`,  `remote_embedding_num_tries` and `remote_embedding_batch_size` parameters

Documented here: https://typesense.org/docs/0.25.1/api/vector-search.html#remote-embedding-api-parameters

**Comment by jdriscoll98** [comment]
> I have indeed seen timeouts with OpenAI APIs, depending on time of day (may be due to traffic patterns on the OpenAI side).
Will this cause the document not to be indexed or will it just not have an embedding?

> You can control remote embedding timeouts are retries using `remote_embedding_timeout_ms`, `remote_embedding_num_tries` and `remote_embedding_batch_size` parameters

Looks like you can only use `remote_embedding_timeout_ms` and `remote_embedding_num_tries` for search? I tried reducing `remote_embedding_batch_size` for import to 40 but still get the logs.

**Comment by jdriscoll98** [comment]
Also , maybe not related to this but its on the topic of import errors. Seems like I get this error whenever I run into those OpenAI logs: 

```undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /Users/jack/mxlocker-web/node_modules/typesense/lib/Typesense/Documents.js:151:65
    at Array.map (<anonymous>)
    at Documents.<anonymous> (/Users/jack/mxlocker-web/node_modules/typesense/lib/Typesense/Documents.js:151:34)
    at step (/Users/jack/mxlocker-web/node_modules/typesense/lib/Typesense/Documents.js:48:23)
    at Object.next (/Users/jack/mxlocker-web/node_modules/typesense/lib/Typesense/Documents.js:29:53)
    at fulfilled (/Users/jack/mxlocker-web/node_modules/typesense/lib/Typesense/Documents.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
   ```
   
   Looks like a javascript client bug

**Comment by jdriscoll98** [comment]
Ok so it seems like when openAI does timeout, it does create an import error: 
```
{"code":408,"document":"...","embedding_error":{"error":"OpenAI API timeout.","request":{"body":{"input":["Fasthouse Gear Combo - Size M/28 Fasthouse Riding Gear Gear Gear Combos Used M "],"model":"text-embedding-ada-002"},"method":"POST","url":"https://api.openai.com/v1/embeddings"},"response":{"message":"Server error on remote server. Please try again later."}},"error":"OpenAI API timeout.","success":false}
```

(i omitted the document object for brevity)

this basically makes import + open AI a non-starter since we'll certainly run into timeouts importing 10k+ documents. Ideally, it would index the document and queue embedding generation if openai isn't available. 

I guess an alternative would be to use all-MiniLM-L12-v2 or another built in model, but it would be nice to continue using openai to offload the CPU usage.

**Comment by jdriscoll98** [comment]
So i ended up just importing without auto embedding and then generating the  embeddings myself afterwards.

Interesting thing to note about openAI, I tried doing the embeddings in small batches but still got timeout issues. As soon as I increased the number of inputs I sent to openai in one call, I never got a timeout issue. 

I bring this up because the typesense docs mentions this: 


```
remote_embedding_batch_size | Max size of each batch that will be sent to remote APIs while importing multiple documents at once. Using lower amount will lower timeout risk, but increase number of requests made. | 200
```
specifically `Using lower amount will lower timeout risk, but increase number of requests made`.

but the opposite may be true? I'm not sure how you guys batch internally, but just sharing my findings. :)
