### ISSUE TITLE
Unable to Properly Handle ObjectNotFound When Deleting Non-existent Collection in Binary-Installed Typesense

### ISSUE THREAD

**Issue by justinliu1985** [typesense/typesense#1387]
## Description

I followed the official documentation to install Typesense using the binary, but when attempting to delete a non-existent collection using the Python client, Typesense fails to return ObjectNotFound properly. However, when running it based on the same data files using Docker, this issue does not occur.

This issue prevents the scraper from running and updating data. I tried to address the issue but couldn't identify the cause.I would greatly appreciate your assistance in resolving this matter. 

thank you.

## Metadata

**Typesense Version**:0.25.1

**OS**:Debian12

Traceback (most recent call last):
  File "/home/justin/appdata/scraper/venv/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/justin/appdata/scraper/docsearch", line 5, in <module>
    run()
  File "/home/justin/appdata/scraper/cli/src/index.py", line 147, in run
    exit(command.run(sys.argv[2:]))
  File "/home/justin/appdata/scraper/cli/src/commands/run_config.py", line 21, in run
    return run_config(args[0])
  File "/home/justin/appdata/scraper/cli/../scraper/src/index.py", line 45, in run_config
    typesense_helper.create_tmp_collection()
  File "/home/justin/appdata/scraper/cli/../scraper/src/typesense_helper.py", line 33, in create_tmp_collection
    self.typesense_client.collections[self.collection_name_tmp].delete()
  File "/home/justin/appdata/scraper/venv/lib/python3.10/site-packages/typesense/collection.py", line 22, in delete
    return self.api_call.delete(self._endpoint_path())
  File "/home/justin/appdata/scraper/venv/lib/python3.10/site-packages/typesense/api_call.py", line 158, in delete
    return self.make_request(requests.delete, endpoint, True,
  File "/home/justin/appdata/scraper/venv/lib/python3.10/site-packages/typesense/api_call.py", line 129, in make_request
    raise last_exception
  File "/home/justin/appdata/scraper/venv/lib/python3.10/site-packages/typesense/api_call.py", line 113, in make_request
    error_message = r.json().get('message', 'API error.')
  File "/home/justin/appdata/scraper/venv/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1

**Comment by justinliu1985** [comment]
When deleting a temporary collection and the name does not exist, running Typesense in Docker returns typesense.exceptions.ObjectNotFound: [Errno 404] No collection with name 'notexist' found.. However, when using Typesense compiled from source code (without any modifications), it returns json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) and leads to an error. What causes this issue, and how can it be resolved?

**Comment by justinliu1985** [comment]
The server is using version 0.25.1, and I noticed that it requires a Python client version greater than or equal to 0.16. However, the scraper requires a client version of 0.10. If you upgrade to 0.16, it will result in an API error.

**Comment by justinliu1985** [comment]
Well, I replaced the files in the 0.25.1 image with the locally compiled binary file, and then ran the new image using Docker. Now, it can update data normally.
