### ISSUE TITLE
Crash typesense server with too many collections ?

### ISSUE THREAD

**Issue by piolet** [typesense/typesense#163]
## Description

I'll try to explain my problem. Sorry for my english ;)
I'm trying to load about 800 collections with between 1 and 20,000 documents to do a load test.
But during indexing, when I reach the halfway point, the typesense server systematically crashes :
```
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to 10.0.0.2 port 8108: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://10.0.0.2:8108/collections/36509347056d46afd43aec in /var/www/html/api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210
Stack trace:
#0 /var/www/html/api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /var/www/html/api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /var/www/html/api/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\Cu in /var/www/html/api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 210
```
I try to restart the process after the crash. It restarts to try to index a new collection but crashes a short time later.
to give a bit of context, my collections have this schema :

```
$schema = [
	"name" => $collection,
	"fields" => [
		['name' => 'id', 'type' => "string"],
		['name' => 'last_name', 'type' => "string"],
		['name' => 'first_name', 'type' => "string"],
		['name' => 'blacklisted', 'type' => "bool"],
		['name' => 'deceased', 'type' => "bool"],
		['name' => 'profession', 'type' => "string"],
		['name' => 'birth_date', 'type' => "string"], // "1949-11-19T00:00:00+01:00"
		['name' => 'email', 'type' => "string"],
		['name' => 'gender', 'type' => "int32"],
		['name' => 'phone', 'type' => "string"],
		['name' => 'address', 'type' => "string"],
		['name' => 'last_name_sort', 'type' => "int64"], // 9 first last_name's chars convert into int : a => 01, b => 02, etc., space => 00
		['name' => 'first_name_sort', 'type' => "int64"], // same last_name_sort
		['name' => 'last_name_initial', 'type' => "string", "facet" => true], // first last_name char to do a start_with query
		['name' => 'first_name_initial', 'type' => "string", "facet" => true] // same last_name_initial
	],
	"default_sorting_field" => "last_name_sort"
];
```

I use docker to do this. And when i launch docker stats command, i have this stats :
```
CONTAINER ID        NAME                    CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
7544a5d316b3        typesense_typesense_1   1.08%               1.016GiB / 1.941GiB   52.38%              9.19kB / 214kB      8.88GB / 0B         985

```

the memory is not yet completely saturated however.

## Steps to reproduce

I use the php client to manage this indexing, like this :
```
$documents = $this->get_all_patients($user);
if (empty($documents)) return;
			
echo "updating... ".count($documents)." patients\n";
// to avoid out of memory exception, i split my indexing by range of 5000 documents
for($i = 0; $i < count($documents); $i += 5000) {
	$sub = array_slice($documents, $i, min(5000, count($documents) - $i));
	try {
		$this->client->collections[$collection]->documents->import($sub, ['action' => 'upsert']);
	} catch (\Exception $e) {
		print_r($sub);
		die($e);
	}
}

```
## Expected Behavior

I would like to be able to index several hundreds of collections without worries

## Actual Behavior

Crash with ConnectException

## Metadata

**Typsense Version**: 0.17

**OS**: Mac OS - Docker

**Comment by kishorenc** [comment]
@piolet When the crash happens, Typesense log will also contain a stack trace: can you also please post that?

**Comment by piolet** [comment]
This last log associated at last crash, is it these logs that you want ? :
```
2020/12/01-12:18:08.026809 7f66af3780c0 [db/db_impl_write.cc:1308] [default] New memtable created with log file: #131. Immutable memtables: 0.
2020/12/01-12:18:08.035744 7f669b3fe700 (Original Log Time 2020/12/01-12:18:08.034633) [db/db_impl_compaction_flush.cc:1349] Calling FlushMemTableToOutputFile with column family [default], flush slots available 4, compaction slots available 1, flush slots scheduled 1, compaction slots scheduled 0
2020/12/01-12:18:08.035752 7f669b3fe700 [db/flush_job.cc:296] [default] [JOB 2] Flushing memtable with next log file: 131
2020/12/01-12:18:08.036684 7f669b3fe700 EVENT_LOG_v1 {"time_micros": 1606825088036079, "job": 2, "event": "flush_started", "num_memtables": 1, "num_entries": 21806, "num_deletes": 0, "memory_usage": 4065640, "flush_reason": "SuperVersion Change"}
2020/12/01-12:18:08.036830 7f669b3fe700 [db/flush_job.cc:326] [default] [JOB 2] Level-0 flush table #134: started
2020/12/01-12:18:08.090507 7f669b3fe700 EVENT_LOG_v1 {"time_micros": 1606825088090474, "cf_name": "default", "job": 2, "event": "table_file_creation", "file_number": 134, "file_size": 3262467, "table_properties": {"data_size": 3234648, "index_size": 26886, "filter_size": 0, "raw_key_size": 424451, "raw_average_key_size": 29, "raw_value_size": 2893594, "raw_average_value_size": 199, "num_data_blocks": 831, "num_entries": 14515, "filter_policy_name": "", "kDeletedKeys": "0", "kMergeOperands": "0"}}
2020/12/01-12:18:08.091563 7f669b3fe700 [db/flush_job.cc:366] [default] [JOB 2] Level-0 flush table #134: 3262467 bytes OK
2020/12/01-12:18:08.091989 7f669b3fe700 [db/version_set.cc:2825] Creating manifest 135
2020/12/01-12:18:08.108627 7f669b3fe700 (Original Log Time 2020/12/01-12:18:08.091928) [db/memtable_list.cc:374] [default] Level-0 commit table #134 started
2020/12/01-12:18:08.108633 7f669b3fe700 (Original Log Time 2020/12/01-12:18:08.108207) [db/memtable_list.cc:397] [default] Level-0 commit table #134: memtable #1 done
2020/12/01-12:18:08.108635 7f669b3fe700 (Original Log Time 2020/12/01-12:18:08.108229) EVENT_LOG_v1 {"time_micros": 1606825088108220, "job": 2, "event": "flush_finished", "output_compression": "NoCompression", "lsm_state": [2, 12, 0, 0, 0, 0, 0], "immutable_memtables": 0}
2020/12/01-12:18:08.108638 7f669b3fe700 (Original Log Time 2020/12/01-12:18:08.108352) [db/db_impl_compaction_flush.cc:146] [default] Level summary: base level 1 max bytes base 536870912 files[2 12 0 0 0 0 0] max score 1.00
2020/12/01-12:18:08.112776 7f669f1ff700 [WARN] [db/db_impl.cc:488] ------- DUMPING STATS -------
2020/12/01-12:18:08.112834 7f669f1ff700 [WARN] [db/db_impl.cc:489] 
** DB Stats **
Uptime(secs): 197.2 total, 197.2 interval
Cumulative writes: 15K writes, 22K keys, 15K commit groups, 1.0 writes per commit group, ingest: 0.00 GB, 0.02 MB/s
Cumulative WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 GB, 0.00 MB/s
Cumulative stall: 00:00:0.000 H:M:S, 0.0 percent
Interval writes: 15K writes, 22K keys, 15K commit groups, 1.0 writes per commit group, ingest: 3.69 MB, 0.02 MB/s
Interval WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Interval stall: 00:00:0.000 H:M:S, 0.0 percent

** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
----------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      2/0    5.97 MB   1.0      0.0     0.0      0.0       0.0      0.0       0.0   1.0      0.0     55.3         0         1    0.056       0      0
  L1     12/0   202.93 MB   0.4      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
 Sum     14/0   208.89 MB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   1.0      0.0     55.3         0         1    0.056       0      0
 Int      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   1.0      0.0     55.3         0         1    0.056       0      0
Uptime(secs): 197.2 total, 197.2 interval
Flush(GB): cumulative 0.003, interval 0.003
AddFile(GB): cumulative 0.000, interval 0.000
AddFile(Total Files): cumulative 0, interval 0
AddFile(L0 Files): cumulative 0, interval 0
AddFile(Keys): cumulative 0, interval 0
Cumulative compaction: 0.00 GB write, 0.02 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.1 seconds
Interval compaction: 0.00 GB write, 0.02 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.1 seconds
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count

** File Read Latency Histogram By Level [default] **

** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
----------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      2/0    5.97 MB   1.0      0.0     0.0      0.0       0.0      0.0       0.0   1.0      0.0     55.3         0         1    0.056       0      0
  L1     12/0   202.93 MB   0.4      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
 Sum     14/0   208.89 MB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   1.0      0.0     55.3         0         1    0.056       0      0
 Int      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
Uptime(secs): 197.2 total, 0.0 interval
Flush(GB): cumulative 0.003, interval 0.000
AddFile(GB): cumulative 0.000, interval 0.000
AddFile(Total Files): cumulative 0, interval 0
AddFile(L0 Files): cumulative 0, interval 0
AddFile(Keys): cumulative 0, interval 0
Cumulative compaction: 0.00 GB write, 0.02 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.1 seconds
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count

** File Read Latency Histogram By Level [default] **
2020/12/01-12:18:08.114328 7f669f1ff700 [db/compaction_job.cc:1484] [default] [JOB 3] Compacting 2@0 + 4@1 files to L1, score 1.00
2020/12/01-12:18:08.114338 7f669f1ff700 [db/compaction_job.cc:1488] [default] Compaction start summary: Base version 2 Base level 0, inputs: [134(3186KB) 129(2922KB)], [126(64MB) 127(64MB) 128(19MB) 72(6399KB)]
2020/12/01-12:18:08.114555 7f669f1ff700 EVENT_LOG_v1 {"time_micros": 1606825088114356, "job": 3, "event": "compaction_started", "files_L0": [134, 129], "files_L1": [126, 127, 128, 72], "score": 1, "input_data_size": 168891621}
2020/12/01-12:18:09.363531 7f669f1ff700 [db/compaction_job.cc:1162] [default] [JOB 3] Generated table #136: 298373 keys, 67680836 bytes
2020/12/01-12:18:09.363556 7f669f1ff700 EVENT_LOG_v1 {"time_micros": 1606825089363544, "cf_name": "default", "job": 3, "event": "table_file_creation", "file_number": 136, "file_size": 67680836, "table_properties": {"data_size": 67112873, "index_size": 567031, "filter_size": 0, "raw_key_size": 8735299, "raw_average_key_size": 29, "raw_value_size": 60041080, "raw_average_value_size": 201, "num_data_blocks": 17241, "num_entries": 298373, "filter_policy_name": "", "kDeletedKeys": "0", "kMergeOperands": "0"}}
2020/12/01-12:18:10.434321 7f669f1ff700 [db/compaction_job.cc:1162] [default] [JOB 3] Generated table #137: 293612 keys, 67679766 bytes
2020/12/01-12:18:10.434345 7f669f1ff700 EVENT_LOG_v1 {"time_micros": 1606825090434334, "cf_name": "default", "job": 3, "event": "table_file_creation", "file_number": 137, "file_size": 67679766, "table_properties": {"data_size": 67111584, "index_size": 567250, "filter_size": 0, "raw_key_size": 8552560, "raw_average_key_size": 29, "raw_value_size": 60211077, "raw_average_value_size": 205, "num_data_blocks": 17230, "num_entries": 293612, "filter_policy_name": "", "kDeletedKeys": "0", "kMergeOperands": "0"}}
2020/12/01-12:18:11.114457 7f669f1ff700 [db/compaction_job.cc:1162] [default] [JOB 3] Generated table #138: 147235 keys, 33529603 bytes
2020/12/01-12:18:11.114480 7f669f1ff700 EVENT_LOG_v1 {"time_micros": 1606825091114470, "cf_name": "default", "job": 3, "event": "table_file_creation", "file_number": 138, "file_size": 33529603, "table_properties": {"data_size": 33250147, "index_size": 278525, "filter_size": 0, "raw_key_size": 4269822, "raw_average_key_size": 29, "raw_value_size": 29783473, "raw_average_value_size": 202, "num_data_blocks": 8520, "num_entries": 147235, "filter_policy_name": "", "kDeletedKeys": "0", "kMergeOperands": "0"}}
2020/12/01-12:18:11.115503 7f669f1ff700 [db/compaction_job.cc:1236] [default] [JOB 3] Compacted 2@0 + 4@1 files to L1 => 168890205 bytes
2020/12/01-12:18:11.117560 7f669f1ff700 (Original Log Time 2020/12/01-12:18:11.117106) [db/compaction_job.cc:640] [default] compacted to: base level 1 max bytes base 536870912 files[0 11 0 0 0 0 0] max score 0.41, MB/sec: 56.3 rd, 56.3 wr, level 1, files in(2, 4) out(3) MB in(6.0, 155.1) out(161.1), read-write-amplify(54.0) write-amplify(27.0) OK, records in: 739223, records dropped: 2 output_compression: NoCompression
2020/12/01-12:18:11.117568 7f669f1ff700 (Original Log Time 2020/12/01-12:18:11.117150) EVENT_LOG_v1 {"time_micros": 1606825091117144, "job": 3, "event": "compaction_finished", "compaction_time_micros": 2999987, "output_level": 1, "num_output_files": 3, "total_output_size": 168890205, "num_input_records": 739222, "num_output_records": 739220, "num_subcompactions": 1, "output_compression": "NoCompression", "num_single_delete_mismatches": 0, "num_single_delete_fallthrough": 0, "lsm_state": [0, 11, 0, 0, 0, 0, 0]}
2020/12/01-12:18:11.128232 7f669f1ff700 EVENT_LOG_v1 {"time_micros": 1606825091128226, "job": 3, "event": "table_file_deletion", "file_number": 134}
2020/12/01-12:18:11.130270 7f669f1ff700 EVENT_LOG_v1 {"time_micros": 1606825091130266, "job": 3, "event": "table_file_deletion", "file_number": 129}
2020/12/01-12:18:11.132385 7f669f1ff700 EVENT_LOG_v1 {"time_micros": 1606825091132381, "job": 3, "event": "table_file_deletion", "file_number": 128}
2020/12/01-12:18:11.135213 7f669f1ff700 EVENT_LOG_v1 {"time_micros": 1606825091135209, "job": 3, "event": "table_file_deletion", "file_number": 127}
2020/12/01-12:18:11.135675 7f669f1ff700 EVENT_LOG_v1 {"time_micros": 1606825091135672, "job": 3, "event": "table_file_deletion", "file_number": 126}
2020/12/01-12:18:11.140138 7f669f1ff700 EVENT_LOG_v1 {"time_micros": 1606825091140133, "job": 3, "event": "table_file_deletion", "file_number": 72}
2020/12/01-12:18:14.836080 7f66af3780c0 [db/db_impl_write.cc:1308] [default] New memtable created with log file: #131. Immutable memtables: 0.
2020/12/01-12:18:14.838634 7f669d5ff700 (Original Log Time 2020/12/01-12:18:14.838152) [db/db_impl_compaction_flush.cc:1349] Calling FlushMemTableToOutputFile with column family [default], flush slots available 4, compaction slots available 1, flush slots scheduled 1, compaction slots scheduled 0
2020/12/01-12:18:14.838640 7f669d5ff700 [db/flush_job.cc:296] [default] [JOB 4] Flushing memtable with next log file: 131
2020/12/01-12:18:14.839106 7f669d5ff700 EVENT_LOG_v1 {"time_micros": 1606825094838656, "job": 4, "event": "flush_started", "num_memtables": 1, "num_entries": 21452, "num_deletes": 0, "memory_usage": 4065888, "flush_reason": "SuperVersion Change"}
2020/12/01-12:18:14.839334 7f669d5ff700 [db/flush_job.cc:326] [default] [JOB 4] Level-0 flush table #139: started
2020/12/01-12:18:14.881366 7f669d5ff700 EVENT_LOG_v1 {"time_micros": 1606825094881309, "cf_name": "default", "job": 4, "event": "table_file_creation", "file_number": 139, "file_size": 3321278, "table_properties": {"data_size": 3293030, "index_size": 27315, "filter_size": 0, "raw_key_size": 418342, "raw_average_key_size": 29, "raw_value_size": 2956437, "raw_average_value_size": 206, "num_data_blocks": 844, "num_entries": 14308, "filter_policy_name": "", "kDeletedKeys": "0", "kMergeOperands": "1"}}
2020/12/01-12:18:14.881980 7f669d5ff700 [db/flush_job.cc:366] [default] [JOB 4] Level-0 flush table #139: 3321278 bytes OK

```

**Comment by kishorenc** [comment]
Hmm, that seems to be RocksDB logs. Typesense uses RocksDB but it does not actually enable verbose logs on it. Typesense crash log will end like this:

https://user-images.githubusercontent.com/72962877/97819836-1c59ab00-1cbc-11eb-870d-6be7bad60a4a.png

Notice the "Typesense crashed" phrase and the stack trace after that.

**Comment by piolet** [comment]
where can i find this kind of log ? which directory ?

**Comment by kishorenc** [comment]
Run:

```
docker logs <container_id>
```

The crash stack trace will be right at the end. If this does not happen, start Typesense server with a logging directory via the `--log-dir` option. After crash, you can find the log file in that directory.

**Comment by piolet** [comment]
No "crash" mention in log :/ see attachment

[typesense-log.txt](https://github.com/typesense/typesense/files/5623281/typesense-log.txt)

**Comment by kishorenc** [comment]
The server is not crashing but the leader node steps down because it is not able to write to the file system:

```
E20201201 14:31:37.119483    87 log.cpp:417] Fail to write to fd=59, path: /data/state/logInput/output error
E20201201 14:31:37.135149    87 log_manager.cpp:464] Fail to append_entries, nappent=0, to_append=1
E20201201 14:31:37.138787    89 raft_server.h:204] Met peering error {type=LogError, error_code=5, error_text=`Fail to append entries'}
E20201201 14:31:37.137706    87 node.cpp:1864] node default_group:172.21.0.2:8107:8108 append [343, 343] failed
W20201201 14:31:37.138806    89 node.cpp:1264] node default_group:172.21.0.2:8107:8108 got error={type=LogError, error_code=5, error_text=`Fail to append entries'}
I20201201 14:31:37.142379    89 replicator.cpp:1475] Group default_group Fail to find the next candidate
I20201201 14:31:37.144057    89 raft_server.h:196] Node stepped down : Raft node(leader or candidate) is in error.
```

Since the node steps down, further writes are rejected. 

1. Can you please check to see if there is enough disk space and the docker container is not getting throttled somehow? 
2. Can you try running the Typesense server without Docker to see if the same problem occurs?

**Comment by piolet** [comment]
good news.
With a little more memory allocated, like double the amount (4GB instead of 2GB), it works without any worries.

But I don't understand why it crashes with 2Gb, when my process couldn't use more than 1.1Gb before crashing.

**Comment by kishorenc** [comment]
That's odd. I'm not sure why that would happen. You can also try hitting the /metrics.json endpoint to compare the active memory bytes value with what Docker shows to see if they match.

**Comment by piolet** [comment]
like this ?

```
{
  "system_cpu1_active_percentage": "22.22",
  "system_cpu2_active_percentage": "0.00",
  "system_cpu3_active_percentage": "0.00",
  "system_cpu4_active_percentage": "25.00",
  "system_cpu5_active_percentage": "33.33",
  "system_cpu6_active_percentage": "11.11",
  "system_cpu_active_percentage": "17.86",
  "system_disk_total_bytes": "499963174912",
  "system_disk_used_bytes": "109290541056",
  "system_memory_total_bytes": "2083606528",
  "system_memory_used_bytes": "1362706432",
  "system_network_received_bytes": "4027",
  "system_network_sent_bytes": "3937",
  "typesense_memory_active_bytes": "265953280",
  "typesense_memory_allocated_bytes": "259294328",
  "typesense_memory_fragmentation_ratio": "0.03",
  "typesense_memory_mapped_bytes": "351821824",
  "typesense_memory_metadata_bytes": "11431008",
  "typesense_memory_resident_bytes": "265953280",
  "typesense_memory_retained_bytes": "111648768"
}
```

**Comment by kishorenc** [comment]
Yes, so typesense_memory_active_bytes is about 2.6 GB, and that number comes directly from the internal memory allocator and so is the most reliable.

**Comment by piolet** [comment]
So i must just increase the memory allocated. Simple fix :)

thx for your help

**Comment by kishorenc** [comment]
Correct, you are welcome 👍
