### ISSUE TITLE
Malformed JSON returned for bad infix search request

### ISSUE THREAD

**Issue by rovaniemi** [typesense/typesense#1753]
## Description

`Typesense-js` can't parse all jsons returned by `typesense`

## Steps to reproduce

Requests the use of inflix in a collection where the inflix index does not exist.

## Expected Behavior

Typesense-js returns message ```{
	"message": "Could not find `x` in the infix index. Make sure to enable infix search by specifying `"infix": true` in the schema."
}```

## Actual Behavior

Request #1716486279846: Request to Node 0 failed due to "undefined Expected ',' or '}' after property value in JSON at position 108"

```
❗️ SyntaxError: Expected ',' or '}' after property value in JSON at position 108
    at JSON.parse (<anonymous>)
    at Object.requestOptions.transformResponse (/app/node_modules/typesense/src/Typesense/ApiCall.ts:188:40)
    at transform (/app/node_modules/typesense/node_modules/axios/lib/core/transformData.js:18:15)
    at Object.forEach (/app/node_modules/typesense/node_modules/axios/lib/utils.js:245:10)
    at Object.transformData (/app/node_modules/typesense/node_modules/axios/lib/core/transformData.js:17:9)
    at onAdapterResolution (/app/node_modules/typesense/node_modules/axios/lib/core/dispatchRequest.js:62:35)
```

## Metadata

**Typesense Version**: 26.0

**Comment by jasonbosco** [comment]
Fix is now available in `27.0.rc18`
