### ISSUE TITLE
Seems like a bug on filter_by:price which one actually i created field as float datatype.

### ISSUE THREAD

**Issue by rezwanahmedsami** [typesense/typesense#2008]
## Description

```php
if (isset($_GET['min_price']) && isset($_GET['max_price'])) {
        // check not empty
        if (!empty($_GET['min_price']) && !empty($_GET['max_price'])) {
            $min_price = trim($_GET['min_price']);
            $max_price = trim($_GET['max_price']);

            // convert to float
            $min_price = floatval($min_price);
            $max_price = floatval($max_price);
            // check data type
            if (is_float($min_price) && is_float($max_price)) {
                $searchParameters['filter_by'] = 'price:>'.$min_price.',price:<'.$max_price;
            }else{
                die('Invalid data type');
            }
            // $searchParameters['filter_by'] = 'price:>'.$min_price.',price:<'.$max_price;
        }
    }
```

I done this to filter by price min and max
But its throwing me error:

```Fatal error: Uncaught Typesense\Exceptions\RequestMalformed: Error with filter field `price`: Not a float. in /home/epipick.com/public_html/libraries/typesense-php/vendor/typesense/typesense-php/src/ApiCall.php:344 Stack trace: #0 /home/epipick.com/public_html/libraries/typesense-php/vendor/typesense/typesense-php/src/ApiCall.php(237): Typesense\ApiCall->getException() #1 /home/epipick.com/public_html/libraries/typesense-php/vendor/typesense/typesense-php/src/ApiCall.php(106): Typesense\ApiCall->makeRequest() #2 /home/epipick.com/public_html/libraries/typesense-php/vendor/typesense/typesense-php/src/Documents.php(192): Typesense\ApiCall->get() #3 /home/epipick.com/public_html/search2/index.php(86): Typesense\Documents->search() #4 {main} thrown in /home/epipick.com/public_html/libraries/typesense-php/vendor/typesense/typesense-php/src/ApiCall.php on line 344```

i was created the field schema like:
```['name' => 'price', 'type' => 'float', 'facet' => true],```

## Steps to reproduce
Installed by yum in almalinux 9

## Expected Behavior
It should work the filter by price min and max

## Actual Behavior
```Fatal error: Uncaught Typesense\Exceptions\RequestMalformed: Error with filter field `price`: Not a float. in /home/epipick.com/public_html/libraries/typesense-php/vendor/typesense/typesense-php/src/ApiCall.php:344 Stack trace: #0 /home/epipick.com/public_html/libraries/typesense-php/vendor/typesense/typesense-php/src/ApiCall.php(237): Typesense\ApiCall->getException() #1 /home/epipick.com/public_html/libraries/typesense-php/vendor/typesense/typesense-php/src/ApiCall.php(106): Typesense\ApiCall->makeRequest() #2 /home/epipick.com/public_html/libraries/typesense-php/vendor/typesense/typesense-php/src/Documents.php(192): Typesense\ApiCall->get() #3 /home/epipick.com/public_html/search2/index.php(86): Typesense\Documents->search() #4 {main} thrown in /home/epipick.com/public_html/libraries/typesense-php/vendor/typesense/typesense-php/src/ApiCall.php on line 344```

## Metadata

**Typesense Version**: v27.1

**OS**: almalinux 9

**Comment by jasonbosco** [comment]
To help narrow down the issue, could you share a set of curl commands like [this](https://gist.github.com/jasonbosco/7c3432713216c378472f13e72246f46b) that replicates the issue with a minimal dataset?

**Comment by rezwanahmedsami** [comment]
[root@server ~]# curl -X GET "http://localhost:8108/collections" \
  -H "Content-Type: application/json" \
  -H "X-Typesense-Api-Key: <API-KEY>"
[{"created_at":1728677463,"default_sorting_field":"cat_id","enable_nested_fields":false,"fields":[{"facet":false,"index":true,"infix":false,"locale":"","name":"cat_id","optional":false,"sort":true,"stem":false,"store":true,"type":"int64"},{"facet":false,"index":true,"infix":false,"locale":"","name":"level_1","optional":false,"sort":false,"stem":false,"store":true,"type":"string"},{"facet":false,"index":true,"infix":false,"locale":"","name":"level_2","optional":false,"sort":false,"stem":false,"store":true,"type":"string"},{"facet":false,"index":true,"infix":false,"locale":"","name":"cat_url","optional":false,"sort":false,"stem":false,"store":true,"type":"string"},{"facet":false,"index":true,"infix":false,"locale":"","name":"slug","optional":false,"sort":false,"stem":false,"store":true,"type":"string"},{"facet":false,"index":true,"infix":false,"locale":"","name":"current_page","optional":false,"sort":true,"stem":false,"store":true,"type":"int32"},{"facet":false,"index":true,"infix":false,"locale":"","name":"done","optional":false,"sort":true,"stem":false,"store":true,"type":"bool"}],"name":"amazon_categories","num_documents":275,"symbols_to_index":[],"token_separators":[]},{"created_at":1728592948,"default_sorting_field":"rating","enable_nested_fields":true,"fields":[{"facet":false,"index":true,"infix":false,"locale":"","name":"product_id","optional":false,"sort":true,"stem":false,"store":true,"type":"int64"},{"facet":true,"index":true,"infix":false,"locale":"","name":"amazon_cat_id","optional":false,"sort":true,"stem":false,"store":true,"type":"int64"},{"facet":false,"index":true,"infix":false,"locale":"","name":"linked_id","optional":false,"sort":true,"stem":false,"store":true,"type":"int64"},{"facet":false,"index":true,"infix":false,"locale":"","name":"title","optional":false,"sort":false,"stem":false,"store":true,"type":"string"},{"facet":false,"index":true,"infix":false,"locale":"","name":"main_image_url","optional":false,"sort":false,"stem":false,"store":true,"type":"string"},{"facet":false,"index":true,"infix":false,"locale":"","name":"image","optional":true,"sort":false,"stem":false,"store":true,"type":"string"},{"facet":false,"index":true,"infix":false,"locale":"","name":"price_str","optional":false,"sort":false,"stem":false,"store":true,"type":"string"},{"facet":true,"index":true,"infix":false,"locale":"","name":"price","optional":false,"sort":true,"stem":false,"store":true,"type":"float"},{"facet":true,"index":true,"infix":false,"locale":"","name":"currency","optional":false,"sort":false,"stem":false,"store":true,"type":"string"},{"facet":true,"index":true,"infix":false,"locale":"","name":"rating","optional":false,"sort":true,"stem":false,"store":true,"type":"float"},{"facet":false,"index":true,"infix":false,"locale":"","name":"rating_str","optional":false,"sort":false,"stem":false,"store":true,"type":"string"},{"facet":false,"index":true,"infix":false,"locale":"","name":"description","optional":true,"sort":false,"stem":false,"store":true,"type":"string"},{"facet":false,"index":true,"infix":false,"locale":"","name":"features","optional":true,"sort":false,"stem":false,"store":true,"type":"string[]"},{"facet":true,"index":true,"infix":false,"locale":"","name":"brand","optional":true,"sort":false,"stem":false,"store":true,"type":"string"},{"facet":true,"index":true,"infix":false,"locale":"","name":"availability","optional":true,"sort":false,"stem":false,"store":true,"type":"string"},{"facet":false,"index":true,"infix":false,"locale":"","name":"product_details","optional":true,"sort":false,"stem":false,"store":true,"type":"string"},{"facet":false,"index":true,"infix":false,"locale":"","name":"product_information","optional":true,"sort":false,"stem":false,"store":true,"type":"string"},{"facet":false,"index":true,"infix":false,"locale":"","name":"product_original_link","optional":false,"sort":false,"stem":false,"store":true,"type":"string"},{"facet":false,"index":true,"infix":false,"locale":"","name":"product_affiliate_link","optional":false,"sort":false,"stem":false,"store":true,"type":"string"},{"facet":false,"index":true,"infix":false,"locale":"","name":"last_update_time","optional":false,"sort":true,"stem":false,"store":true,"type":"int64"},{"facet":false,"index":true,"infix":false,"locale":"","name":"creation_time","optional":false,"sort":true,"stem":false,"store":true,"type":"int64"},{"facet":true,"index":true,"infix":false,"locale":"","name":"done","optional":false,"sort":true,"stem":false,"store":true,"type":"bool"}],"name":"amazon_products","num_documents":70356,"symbols_to_index":[],"token_separators":[]}]

**Comment by jasonbosco** [comment]
The curl commands you posted do not replicate the error you shared originally.

**Comment by rezwanahmedsami** [comment]
> The curl commands you posted do not replicate the error you shared originally. 

Because what i am searching for is this. Its not throwing an error.

Its giving me the same message likr i gave you.

Curl only returning Not found for every command of search.

But php library throwing error

**Comment by jasonbosco** [comment]
The curl command you shared [here](https://github.com/typesense/typesense/issues/2008#issuecomment-2408102490) is not valid though, which is why you're seeing a 404. POST is only supported with the `multi_search` endpoint. 

You want to follow the curl commands I shared in my link above exactly and only change the data pieces as needed to replicate the issue: https://gist.github.com/jasonbosco/7c3432713216c378472f13e72246f46b

**Comment by rezwanahmedsami** [comment]
> curl -X POST "http://localhost:8108/collections/amazon_products/documents/search"
> -H "Content-Type: application/json"
> -H "X-Typesense-Api-Key: "
> -d '{
> "q": "*",
> "query_by": "title,description,price_str,features,product_details,product_information",
> "sort_by": "_text_match:desc",
> "per_page": 1,
> "page": 1
> }'

```bash
[root@server ~]# curl -X POST "http://localhost:8108/multi_search" \
-H "Content-Type: application/json" \
-H "X-Typesense-Api-Key: 0NMFFuonRGf6rELO20XoHUB0KydOqSDCMPvRfUNUrdoprfXF" \
-d '{
  "searches": [
    {
      "collection": "amazon_products",
      "q": "laptop",
      "query_by": "title,description,price_str,features,product_details,product_information",
      "filter_by": "price:>=30.00,price:<=1000.00",
      "sort_by": "_text_match:desc",
      "per_page": 1,
      "page": 1
    }
  ]
}'
{"results":[{"code":400,"error":"Error with filter field `price`: Not a float."}]}[root@server ~]#
```

Watch this now, its saying error with filter price not float, which is totally wrong.

because my price field is float:
```bash
[root@server ~]# curl -H "X-TYPESENSE-API-KEY: 0NMFFuonRGf6rELO20XoHUB0KydOqSDCMPvRfUNUrdoprfXF" \
       -X GET \
       "http://localhost:8108/collections/amazon_products" | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3414    0  3414    0     0   666k      0 --:--:-- --:--:-- --:--:--  666k
{
  "created_at": 1729538009,
  "default_sorting_field": "rating",
  "enable_nested_fields": true,
  "fields": [
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "product_id",
      "optional": false,
      "sort": true,
      "stem": false,
      "store": true,
      "type": "int64"
    },
    {
      "facet": true,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "amazon_cat_id",
      "optional": false,
      "sort": true,
      "stem": false,
      "store": true,
      "type": "int64"
    },
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "linked_id",
      "optional": false,
      "sort": true,
      "stem": false,
      "store": true,
      "type": "int64"
    },
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "title",
      "optional": false,
      "sort": false,
      "stem": false,
      "store": true,
      "type": "string"
    },
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "main_image_url",
      "optional": false,
      "sort": false,
      "stem": false,
      "store": true,
      "type": "string"
    },
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "image",
      "optional": true,
      "sort": false,
      "stem": false,
      "store": true,
      "type": "string"
    },
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "price_str",
      "optional": false,
      "sort": false,
      "stem": false,
      "store": true,
      "type": "string"
    },
    {
      "facet": true,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "price",
      "optional": false,
      "sort": true,
      "stem": false,
      "store": true,
      "type": "float"
    },
    {
      "facet": true,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "currency",
      "optional": false,
      "sort": false,
      "stem": false,
      "store": true,
      "type": "string"
    },
    {
      "facet": true,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "rating",
      "optional": false,
      "sort": true,
      "stem": false,
      "store": true,
      "type": "float"
    },
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "rating_str",
      "optional": false,
      "sort": false,
      "stem": false,
      "store": true,
      "type": "string"
    },
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "description",
      "optional": true,
      "sort": false,
      "stem": false,
      "store": true,
      "type": "string"
    },
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "features",
      "optional": true,
      "sort": false,
      "stem": false,
      "store": true,
      "type": "string[]"
    },
    {
      "facet": true,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "brand",
      "optional": true,
      "sort": false,
      "stem": false,
      "store": true,
      "type": "string"
    },
    {
      "facet": true,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "availability",
      "optional": true,
      "sort": false,
      "stem": false,
      "store": true,
      "type": "string"
    },
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "product_details",
      "optional": true,
      "sort": false,
      "stem": false,
      "store": true,
      "type": "string"
    },
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "product_information",
      "optional": true,
      "sort": false,
      "stem": false,
      "store": true,
      "type": "string"
    },
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "product_original_link",
      "optional": false,
      "sort": false,
      "stem": false,
      "store": true,
      "type": "string"
    },
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "product_affiliate_link",
      "optional": false,
      "sort": false,
      "stem": false,
      "store": true,
      "type": "string"
    },
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "last_update_time",
      "optional": false,
      "sort": true,
      "stem": false,
      "store": true,
      "type": "int64"
    },
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "creation_time",
      "optional": false,
      "sort": true,
      "stem": false,
      "store": true,
      "type": "int64"
    },
    {
      "facet": true,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "done",
      "optional": false,
      "sort": true,
      "stem": false,
      "store": true,
      "type": "bool"
    }
  ],
  "name": "amazon_products",
  "num_documents": 100987,
  "symbols_to_index": [],
  "token_separators": []
}
```


watch here field price is float:
    {
      "facet": true,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "price",
      "optional": false,
      "sort": true,
      "stem": false,
      "store": true,
      "type": "float"
    },

**Comment by jasonbosco** [comment]
This syntax for filter_by is incorrect:

```
"filter_by": "price:>=30.00,price:<=1000.00"
```

It should instead be:

```
"filter_by": "price:>=30.00 && price:<=1000.00"
```

(use `&&` instead of `,` to AND queries)

**Comment by rezwanahmedsami** [comment]
> This syntax for filter_by is incorrect:
> 
> ```
> "filter_by": "price:>=30.00,price:<=1000.00"
> ```
> 
> It should instead be:
> 
> ```
> "filter_by": "price:>=30.00 && price:<=1000.00"
> ```
> 
> (use `&&` instead of `,` to AND queries)

Thanks a lot, this problem fixed my issue.

But you should validate the query more and put the proper error because the error is confusing.

You should validate the syntax in the query more perfectly.

**Comment by rezwanahmedsami** [comment]
I can fix it and create a pull request.
Do I need to create a new issue on that?
And how do I assign myself to the issue?
