### ISSUE TITLE
following "search for documentation" docs does not work

### ISSUE THREAD

**Issue by olets** [typesense/typesense#551]
## Description

I can't get up and running with VuePress

## Steps to reproduce

Follow https://typesense.org/docs/guide/docsearch.html:

1. Start with https://github.com/typesense/typesense-website/blob/master/docs-site/docsearch.config.js. Customize urls, versions, and index name
2. Install Docker
3. Install jq
4. Run Typesense
      ```shell
      curl -O https://dl.typesense.org/releases/0.22.2/typesense-server-0.22.2-darwin-amd64.tar.gz tar -xzf typesense-server-0.22.2-darwin-amd64.tar.gz
      export TYPESENSE_API_KEY=xyz
      mkdir /tmp/typesense-data
      ./typesense-server --data-dir=/tmp/typesense-data --api-key=$TYPESENSE_API_KEY --enable-cors
      ```
5. Create an .env with
    ```shell
    TYPESENSE_API_KEY=xyz
    TYPESENSE_HOST=xxx.a1.typesense.net
    TYPESENSE_PORT=443
    TYPESENSE_PROTOCOL=https
    ```
6. Run the scraper
    ```shell
    docker run -it --env-file=./.env -e "CONFIG=$(cat ./docsearch.config.json | jq -r tostring)" typesense/docsearch-scraper
    ```

At this point we have to work around two errors:

1. We didn't install the Docker image
2. Our config is js

In addition I'm on an M1, which the Typesense image doesn't support out of the box

So

1. Back to https://typesense.org/docs/guide/install-typesense.html and `docker pull typesense/typesense:0.22.2`
2. Convert the JS object to JSON and save as a config file

The server is still running, so in another terminal session run 

```shell
docker run --platform=linux/amd64 -it --env-file=./.env -e "CONFIG=$(cat ./docsearch.config.json | jq -r tostring)" typesense/docsearch-scraper
```

## Expected Behavior

A scraped site ready to integrate with my documentation site.

## Actual Behavior

That gives an error:

```shell
docker run --platform=linux/amd64 -it --env-file=./.env -e "CONFIG=$(cat ./docsearch.config.json | jq -r tostring)" typesense/docsearch-scraper
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x4008c92630>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='xxx.a1.typesense.net', port=443): Max retries exceeded with url: /collections/zshAbbr_docs_1647401243 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x4008c92630>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/src/index.py", line 116, in <module>
    run_config(environ['CONFIG'])
  File "/root/src/index.py", line 43, in run_config
    typesense_helper.create_tmp_collection()
  File "/root/src/typesense_helper.py", line 30, in create_tmp_collection
    self.typesense_client.collections[self.collection_name_tmp].delete()
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/typesense/collection.py", line 22, in delete
    return self.api_call.delete(self._endpoint_path())
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/typesense/api_call.py", line 159, in delete
    params=params, timeout=self.config.connection_timeout_seconds)
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/typesense/api_call.py", line 129, in make_request
    raise last_exception
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/typesense/api_call.py", line 103, in make_request
    r = fn(url, headers={ApiCall.API_KEY_HEADER_NAME: self.config.api_key}, **kwargs)
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/requests/api.py", line 161, in delete
    return request('delete', url, **kwargs)
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='xxx.a1.typesense.net', port=443): Max retries exceeded with url: /collections/zshAbbr_docs_1647401243 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x4008c92630>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

I can image that `TYPESENSE_API_KEY=xyz` and `TYPESENSE_HOST=xxx.a1.typesense.net` are part of my problem — maybe I'm expected to replace these with "real" values. But I don't know what those would be.

## Metadata

**Typsense Version**: 0.22.2

**OS**:  macOS 12.2.1

**Comment by olets** [comment]
Thanks for your help!

Ok, I didn't realize that the "if you're running Typesense on `localhost`" applied to me. Changing `TYPESENSE_HOST=xxx.a1.typesense.net` to `TYPESENSE_HOST=host.docker.internal` I get nearly the same error logs. Looks like the host change did help — where before I had

> socket.gaierror: [Errno -2] Name or service not known

I now have

> ConnectionRefusedError: [Errno 111] Connection refused

Most of my Docker experience is with Docker Compose. Maybe I'm missing some step that more experienced `docker run` users don't need explicitly documented?

```shell
% docker run --platform=linux/amd64 -it --env-file=./.env -e "CONFIG=$(cat ./docsearch.config.json | jq -r tostring)" typesense/docsearch-scraper
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x4008e23278>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='host.docker.internal', port=443): Max retries exceeded with url: /collections/zshAbbr_docs_1647549100 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x4008e23278>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/src/index.py", line 116, in <module>
    run_config(environ['CONFIG'])
  File "/root/src/index.py", line 43, in run_config
    typesense_helper.create_tmp_collection()
  File "/root/src/typesense_helper.py", line 30, in create_tmp_collection
    self.typesense_client.collections[self.collection_name_tmp].delete()
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/typesense/collection.py", line 22, in delete
    return self.api_call.delete(self._endpoint_path())
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/typesense/api_call.py", line 159, in delete
    params=params, timeout=self.config.connection_timeout_seconds)
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/typesense/api_call.py", line 129, in make_request
    raise last_exception
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/typesense/api_call.py", line 103, in make_request
    r = fn(url, headers={ApiCall.API_KEY_HEADER_NAME: self.config.api_key}, **kwargs)
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/requests/api.py", line 161, in delete
    return request('delete', url, **kwargs)
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='host.docker.internal', port=443): Max retries exceeded with url: /collections/zshAbbr_docs_1647549100 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x4008e23278>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by jasonbosco** [comment]
Running `./typesense-server --data-dir=/tmp/typesense-data --api-key=$TYPESENSE_API_KEY --enable-cors` starts Typesense on port 8108 by default. 

So you'd need to also update `TYPESENSE_PORT=8108` and `TYPESENSE_PROTOCOL=http` in the env file.

**Comment by olets** [comment]
For completeness, here are the server logs

```shell
% ./typesense-server --data-dir=/tmp/typesense-data --api-key=$TYPESENSE_API_KEY --enable-cors
I20220317 10:24:22.201941 88176128 typesense_server_utils.cpp:306] Starting Typesense 0.22.2
I20220317 10:24:22.202582 88176128 typesense_server_utils.cpp:309] Typesense is using jemalloc.
I20220317 10:24:22.203192 88176128 typesense_server_utils.cpp:358] Thread pool size: 64
I20220317 10:24:22.215682 88176128 store.h:61] Initializing DB by opening state dir: /tmp/typesense-data/db
I20220317 10:24:22.235847 88176128 store.h:61] Initializing DB by opening state dir: /tmp/typesense-data/meta
I20220317 10:24:22.262908 88176128 typesense_server_utils.cpp:437] Starting API service...
I20220317 10:24:22.263130 88176128 http_server.cpp:172] Typesense has started listening on port 8108
I20220317 10:24:22.263157 245579776 typesense_server_utils.cpp:209] Since no --nodes argument is provided, starting a single node Typesense cluster.
I20220317 10:24:22.263422 246116352 batched_indexer.cpp:120] Starting batch indexer with 64 threads.
I20220317 10:24:22.274741 245579776 server.cpp:1045] Server[braft::RaftStatImpl+braft::FileServiceImpl+braft::RaftServiceImpl+braft::CliServiceImpl] is serving on port=8107.
I20220317 10:24:22.277221 246116352 batched_indexer.cpp:126] BatchedIndexer skip_index: -9999
I20220317 10:24:22.274777 245579776 server.cpp:1048] Check out http://REDACTED.lan:8107 in web browser.
I20220317 10:24:22.290336 245579776 raft_server.cpp:65] Nodes configuration: 192.168.86.21:8107:8108
I20220317 10:24:22.290796 245579776 raft_server.cpp:104] Snapshot does not exist. We will remove db dir and init db fresh.
I20220317 10:24:22.292145 245579776 store.h:283] rm /tmp/typesense-data/db success
I20220317 10:24:22.292205 245579776 store.h:61] Initializing DB by opening state dir: /tmp/typesense-data/db
I20220317 10:24:22.309350 245579776 store.h:307] DB open success!
I20220317 10:24:22.309374 245579776 raft_server.cpp:469] Loading collections from disk...
I20220317 10:24:22.309381 245579776 collection_manager.cpp:117] CollectionManager::load()
I20220317 10:24:22.309628 245579776 auth_manager.cpp:32] Indexing 0 API key(s) found on disk.
I20220317 10:24:22.309641 245579776 collection_manager.cpp:137] Loading 32 collections in parallel, 1000 documents at a time.
I20220317 10:24:22.309651 245579776 collection_manager.cpp:144] Found 0 collection(s) on disk.
I20220317 10:24:22.318859 245579776 collection_manager.cpp:206] Loaded 0 collection(s).
I20220317 10:24:22.320386 245579776 collection_manager.cpp:210] Initializing batched indexer from snapshot state...
I20220317 10:24:22.320480 245579776 raft_server.cpp:476] Finished loading collections from disk.
I20220317 10:24:22.328775 245579776 log.cpp:677] Use murmurhash32 as the checksum type of appending entries
I20220317 10:24:22.335270 245579776 log.cpp:1158] log load_meta /tmp/typesense-data/state/log/log_meta first_log_index: 1 time: 6440
I20220317 10:24:22.335541 245579776 log.cpp:1098] load open segment, path: /tmp/typesense-data/state/log first_index: 1
I20220317 10:24:22.342906 245579776 raft_meta.cpp:521] Loaded single stable meta, path /tmp/typesense-data/state/meta term 4 votedfor 192.168.86.21:8107:8108 time: 3147
I20220317 10:24:22.346434 245579776 raft_meta.cpp:521] Loaded single stable meta, path /tmp/typesense-data/state/meta term 4 votedfor 192.168.86.21:8107:8108 time: 59
I20220317 10:24:22.346486 245579776 node.cpp:576] node default_group:192.168.86.21:8107:8108 init, term: 4 last_log_id: (index=3,term=4) conf: 192.168.86.21:8107:8108 old_conf: 
I20220317 10:24:22.349778 245579776 node.cpp:1549] node default_group:192.168.86.21:8107:8108 term 4 start vote and grant vote self
I20220317 10:24:22.351612 245579776 raft_meta.cpp:546] Saved single stable meta, path /tmp/typesense-data/state/meta term 5 votedfor 192.168.86.21:8107:8108 time: 923
I20220317 10:24:22.351687 245579776 node.cpp:1783] node default_group:192.168.86.21:8107:8108 term 5 become leader of group 192.168.86.21:8107:8108 
I20220317 10:24:22.355603 245579776 raft_server.cpp:127] Node last_index: 3
I20220317 10:24:22.355643 245579776 typesense_server_utils.cpp:260] Typesense peering service is running on 192.168.86.21:8107
I20220317 10:24:22.355649 245579776 typesense_server_utils.cpp:261] Snapshot interval configured as: 3600s
W20220317 10:24:22.355661 245579776 controller.cpp:1454] SIGINT was installed with 1
I20220317 10:24:22.355682 245579776 raft_server.cpp:524] Term: 5, last_index index: 3, committed_index: 0, known_applied_index: 0, applying_index: 0, queued_writes: 0, pending_queue_size: 1, local_sequence: 0
W20220317 10:24:22.355700 245579776 node.cpp:811] [default_group:192.168.86.21:8107:8108 ] Refusing concurrent configuration changing
E20220317 10:24:22.355722 245579776 raft_server.cpp:578] Node not ready yet (known_applied_index is 0).
E20220317 10:24:22.355773 267579392 raft_server.h:61] Peer refresh failed, error: Doing another configuration change
I20220317 10:24:22.356024 265969664 raft_server.h:251] Configuration of this group is 192.168.86.21:8107:8108
I20220317 10:24:22.356041 265969664 raft_server.h:251] Configuration of this group is 192.168.86.21:8107:8108
I20220317 10:24:22.356050 265969664 raft_server.h:251] Configuration of this group is 192.168.86.21:8107:8108
I20220317 10:24:22.356055 265969664 raft_server.h:251] Configuration of this group is 192.168.86.21:8107:8108
I20220317 10:24:22.359073 265969664 node.cpp:3142] node default_group:192.168.86.21:8107:8108 reset ConfigurationCtx, new_peers: 192.168.86.21:8107:8108, old_peers: 192.168.86.21:8107:8108
I20220317 10:24:22.359135 265969664 raft_server.h:234] Node becomes leader, term: 5
I20220317 10:24:32.391618 245579776 raft_server.cpp:524] Term: 5, last_index index: 4, committed_index: 4, known_applied_index: 4, applying_index: 0, queued_writes: 0, pending_queue_size: 0, local_sequence: 0
I20220317 10:24:32.391942 264896512 raft_server.h:59] Peer refresh succeeded!
```

and then the last two repeat.

And here's `./docsearch.config.json`:

```json
{
  "index_name": "zshAbbr_docs",
  "start_urls": [
      {
          "url": "https://zsh-abbr.olets.dev/",
          "variables": {
              "version": {
                  "zshAbbrLatestVersion": "5.0.0-beta.1",
                  "zshAbbrVersions": [
                      "5.0.0-beta.1"
                  ]
              }
          }
      }
  ],
  "selectors": {
      "default": {
          "lvl0": ".content__default h1",
          "lvl1": ".content__default h2",
          "lvl2": ".content__default h3",
          "lvl3": ".content__default h4",
          "lvl4": ".content__default h5",
          "text": ".content__default p, .content__default ul li, .content__default table tbody tr"
      }
  },
  "scrape_start_urls": false,
  "strip_chars": " .,;:#"
}

**Comment by olets** [comment]
Thanks for the speedy response!! Makes sense, knowing that I now see it in the server logs.

**Comment by olets** [comment]
Success. The last change I needed to make was replacing `.content__default` in the config file with `.theme-default-content`. I'm using Vuepress 2. Haven't used Vuepress 1, guessing it's a v1/v2 change.
